import { ReactComponent as Face1 } from "../assets/svgs/Face1.svg";
import { ReactComponent as Face2 } from "../assets/svgs/Face2.svg";
import { ReactComponent as Face3 } from "../assets/svgs/Face3.svg";
import { ReactComponent as Face4 } from "../assets/svgs/Face4.svg";

export const creatorActiveData = [
  {
    creatorId: 1,
    creatorName: "Vincet Nate",
    CreatorIcon: Face1,
    creatorHandle: "@annan",
    paymentMod: "Expedited",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 2,
    creatorName: "Terry Mango",
    CreatorIcon: Face2,
    creatorHandle: "@mangojuice",
    paymentMod: "Standard",
    approval: "Approved",
    approvalTheme: "#DBE9CF",
  },
  {
    creatorId: 3,
    creatorName: "Corey Siphron",
    CreatorIcon: Face3,
    creatorHandle: "@coreysiphron",
    paymentMod: "Standard",
    approval: "Invited",
    approvalTheme: "#C9DAF0",
  },
  {
    creatorId: 4,
    creatorName: "Martin Schleizer",
    CreatorIcon: Face4,
    creatorHandle: "@scoressemar",
    paymentMod: "Standard",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 5,
    creatorName: "Vincet Nate",
    CreatorIcon: Face1,
    creatorHandle: "@annan",
    paymentMod: "Expedited",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 6,
    creatorName: "Terry Mango",
    CreatorIcon: Face2,
    creatorHandle: "@mangojuice",
    paymentMod: "Standard",
    approval: "Approved",
    approvalTheme: "#DBE9CF",
  },
  {
    creatorId: 7,
    creatorName: "Corey Siphron",
    CreatorIcon: Face3,
    creatorHandle: "@coreysiphron",
    paymentMod: "Standard",
    approval: "Invited",
    approvalTheme: "#C9DAF0",
  },
  {
    creatorId: 8,
    creatorName: "Martin Schleizer",
    CreatorIcon: Face4,
    creatorHandle: "@scoressemar",
    paymentMod: "Standard",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 9,
    creatorName: "Vincet Nate",
    CreatorIcon: Face1,
    creatorHandle: "@annan",
    paymentMod: "Expedited",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 10,
    creatorName: "Terry Mango",
    CreatorIcon: Face2,
    creatorHandle: "@mangojuice",
    paymentMod: "Standard",
    approval: "Approved",
    approvalTheme: "#DBE9CF",
  },
  {
    creatorId: 11,
    creatorName: "Corey Siphron",
    CreatorIcon: Face3,
    creatorHandle: "@coreysiphron",
    paymentMod: "Standard",
    approval: "Invited",
    approvalTheme: "#C9DAF0",
  },
  {
    creatorId: 12,
    creatorName: "Martin Schleizer",
    CreatorIcon: Face4,
    creatorHandle: "@scoressemar",
    paymentMod: "Standard",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 13,
    creatorName: "Vincet Nate",
    CreatorIcon: Face1,
    creatorHandle: "@annan",
    paymentMod: "Expedited",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 14,
    creatorName: "Terry Mango",
    CreatorIcon: Face2,
    creatorHandle: "@mangojuice",
    paymentMod: "Standard",
    approval: "Approved",
    approvalTheme: "#DBE9CF",
  },
  {
    creatorId: 15,
    creatorName: "Corey Siphron",
    CreatorIcon: Face3,
    creatorHandle: "@coreysiphron",
    paymentMod: "Standard",
    approval: "Invited",
    approvalTheme: "#C9DAF0",
  },
  {
    creatorId: 16,
    creatorName: "Martin Schleizer",
    CreatorIcon: Face4,
    creatorHandle: "@scoressemar",
    paymentMod: "Standard",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 17,
    creatorName: "Vincet Nate",
    CreatorIcon: Face1,
    creatorHandle: "@annan",
    paymentMod: "Expedited",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 18,
    creatorName: "Terry Mango",
    CreatorIcon: Face2,
    creatorHandle: "@mangojuice",
    paymentMod: "Standard",
    approval: "Approved",
    approvalTheme: "#DBE9CF",
  },
  {
    creatorId: 19,
    creatorName: "Corey Siphron",
    CreatorIcon: Face3,
    creatorHandle: "@coreysiphron",
    paymentMod: "Standard",
    approval: "Invited",
    approvalTheme: "#C9DAF0",
  },
  {
    creatorId: 20,
    creatorName: "Martin Schleizer",
    CreatorIcon: Face4,
    creatorHandle: "@scoressemar",
    paymentMod: "Standard",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 21,
    creatorName: "Vincet Nate",
    CreatorIcon: Face1,
    creatorHandle: "@annan",
    paymentMod: "Expedited",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
];

export const creatorInvitedData = [
  {
    creatorId: 26,
    creatorName: "Terry Mango",
    CreatorIcon: Face2,
    creatorHandle: "@mangojuice",
    paymentMod: "Standard",
    approval: "Approved",
    approvalTheme: "#DBE9CF",
  },
  {
    creatorId: 27,
    creatorName: "Corey Siphron",
    CreatorIcon: Face3,
    creatorHandle: "@coreysiphron",
    paymentMod: "Standard",
    approval: "Invited",
    approvalTheme: "#C9DAF0",
  },
  {
    creatorId: 28,
    creatorName: "Martin Schleizer",
    CreatorIcon: Face4,
    creatorHandle: "@scoressemar",
    paymentMod: "Standard",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 29,
    creatorName: "Vincet Nate",
    CreatorIcon: Face1,
    creatorHandle: "@annan",
    paymentMod: "Expedited",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 30,
    creatorName: "Terry Mango",
    CreatorIcon: Face2,
    creatorHandle: "@mangojuice",
    paymentMod: "Standard",
    approval: "Approved",
    approvalTheme: "#DBE9CF",
  },
  {
    creatorId: 31,
    creatorName: "Corey Siphron",
    CreatorIcon: Face3,
    creatorHandle: "@coreysiphron",
    paymentMod: "Standard",
    approval: "Invited",
    approvalTheme: "#C9DAF0",
  },
  {
    creatorId: 32,
    creatorName: "Martin Schleizer",
    CreatorIcon: Face4,
    creatorHandle: "@scoressemar",
    paymentMod: "Standard",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 33,
    creatorName: "Vincet Nate",
    CreatorIcon: Face1,
    creatorHandle: "@annan",
    paymentMod: "Expedited",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 34,
    creatorName: "Terry Mango",
    CreatorIcon: Face2,
    creatorHandle: "@mangojuice",
    paymentMod: "Standard",
    approval: "Approved",
    approvalTheme: "#DBE9CF",
  },
  {
    creatorId: 35,
    creatorName: "Corey Siphron",
    CreatorIcon: Face3,
    creatorHandle: "@coreysiphron",
    paymentMod: "Standard",
    approval: "Invited",
    approvalTheme: "#C9DAF0",
  },
];

export const creatorPendingData = [
  {
    creatorId: 36,
    creatorName: "Vincet Nate",
    CreatorIcon: Face1,
    creatorHandle: "@annan",
    paymentMod: "Expedited",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 37,
    creatorName: "Terry Mango",
    CreatorIcon: Face2,
    creatorHandle: "@mangojuice",
    paymentMod: "Standard",
    approval: "Approved",
    approvalTheme: "#DBE9CF",
  },
  {
    creatorId: 38,
    creatorName: "Corey Siphron",
    CreatorIcon: Face3,
    creatorHandle: "@coreysiphron",
    paymentMod: "Standard",
    approval: "Invited",
    approvalTheme: "#C9DAF0",
  },
  {
    creatorId: 39,
    creatorName: "Terry Mango",
    CreatorIcon: Face2,
    creatorHandle: "@mangojuice",
    paymentMod: "Standard",
    approval: "Approved",
    approvalTheme: "#DBE9CF",
  },
  {
    creatorId: 40,
    creatorName: "Corey Siphron",
    CreatorIcon: Face3,
    creatorHandle: "@coreysiphron",
    paymentMod: "Standard",
    approval: "Invited",
    approvalTheme: "#C9DAF0",
  },
];

export const creatorApprovedData = [
  {
    creatorId: 41,
    creatorName: "Corey Siphron",
    CreatorIcon: Face3,
    creatorHandle: "@coreysiphron",
    paymentMod: "Standard",
    approval: "Invited",
    approvalTheme: "#C9DAF0",
  },
  {
    creatorId: 42,
    creatorName: "Vincet Nate",
    CreatorIcon: Face1,
    creatorHandle: "@annan",
    paymentMod: "Expedited",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 43,
    creatorName: "Terry Mango",
    CreatorIcon: Face2,
    creatorHandle: "@mangojuice",
    paymentMod: "Standard",
    approval: "Approved",
    approvalTheme: "#DBE9CF",
  },
  {
    creatorId: 44,
    creatorName: "Corey Siphron",
    CreatorIcon: Face3,
    creatorHandle: "@coreysiphron",
    paymentMod: "Standard",
    approval: "Invited",
    approvalTheme: "#C9DAF0",
  },
  {
    creatorId: 45,
    creatorName: "Vincet Nate",
    CreatorIcon: Face1,
    creatorHandle: "@annan",
    paymentMod: "Expedited",
    approval: "Pending Cost approval",
    approvalTheme: "#F9EECE",
  },
  {
    creatorId: 46,
    creatorName: "Terry Mango",
    CreatorIcon: Face2,
    creatorHandle: "@mangojuice",
    paymentMod: "Standard",
    approval: "Approved",
    approvalTheme: "#DBE9CF",
  },
];
