export const influencerCardData = [
  {
    influencerId: 100,
    influencerName: "Vincet Nate",
    influencerHandle: "@annan",
    totalFollowers: "65M",
    totalPost: "30",
  },
  {
    influencerId: 101,
    influencerName: "Terry Mango",
    influencerHandle: "@mangojuice",
    totalFollowers: "80M",
    totalPost: "72",
  },
  {
    influencerId: 102,
    influencerName: "Corey Siphron",
    influencerHandle: "@coreysiphron",
    totalFollowers: "12M",
    totalPost: "24",
  },
  {
    influencerId: 103,
    influencerName: "Martin Schleizer",
    influencerHandle: "@scoressemar",
    totalFollowers: "22M",
    totalPost: "31",
  },
  {
    influencerId: 104,
    influencerName: "Vincet Nate",
    influencerHandle: "@annan",
    totalFollowers: "65M",
    totalPost: "30",
  },
  {
    influencerId: 105,
    influencerName: "Terry Mango",
    influencerHandle: "@mangojuice",
    totalFollowers: "80M",
    totalPost: "72",
  },
  {
    influencerId: 106,
    influencerName: "Corey Siphron",
    influencerHandle: "@coreysiphron",
    totalFollowers: "12M",
    totalPost: "24",
  },
  {
    influencerId: 107,
    influencerName: "Martin Schleizer",
    influencerHandle: "@scoressemar",
    totalFollowers: "22M",
    totalPost: "31",
  },
  {
    influencerId: 108,
    influencerName: "Vincet Nate",
    influencerHandle: "@annan",
    totalFollowers: "65M",
    totalPost: "30",
  },
  {
    influencerId: 109,
    influencerName: "Terry Mango",
    influencerHandle: "@mangojuice",
    totalFollowers: "80M",
    totalPost: "72",
  },
  {
    influencerId: 110,
    influencerName: "Corey Siphron",
    influencerHandle: "@coreysiphron",
    totalFollowers: "12M",
    totalPost: "24",
  },
  {
    influencerId: 111,
    influencerName: "Martin Schleizer",
    influencerHandle: "@scoressemar",
    totalFollowers: "22M",
    totalPost: "31",
  },
];
